/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.dao.jooq.tables;


import edu.java.scrapper.dao.jooq.DefaultSchema;
import edu.java.scrapper.dao.jooq.Keys;
import edu.java.scrapper.dao.jooq.tables.records.TrackedLinkRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrackedLink extends TableImpl<TrackedLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TRACKED_LINK</code>
     */
    public static final TrackedLink TRACKED_LINK = new TrackedLink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<TrackedLinkRecord> getRecordType() {
        return TrackedLinkRecord.class;
    }

    /**
     * The column <code>TRACKED_LINK.CHAT_ID</code>.
     */
    public final TableField<TrackedLinkRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>TRACKED_LINK.LINK_ID</code>.
     */
    public final TableField<TrackedLinkRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private TrackedLink(Name alias, Table<TrackedLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private TrackedLink(Name alias, Table<TrackedLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TRACKED_LINK</code> table reference
     */
    public TrackedLink(String alias) {
        this(DSL.name(alias), TRACKED_LINK);
    }

    /**
     * Create an aliased <code>TRACKED_LINK</code> table reference
     */
    public TrackedLink(Name alias) {
        this(alias, TRACKED_LINK);
    }

    /**
     * Create a <code>TRACKED_LINK</code> table reference
     */
    public TrackedLink() {
        this(DSL.name("TRACKED_LINK"), null);
    }

    public <O extends Record> TrackedLink(Table<O> child, ForeignKey<O, TrackedLinkRecord> key) {
        super(child, key, TRACKED_LINK);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<TrackedLinkRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_368;
    }

    @Override
    @NotNull
    public List<ForeignKey<TrackedLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_3, Keys.CONSTRAINT_36);
    }

    private transient Chat _chat;
    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null)
            _chat = new Chat(this, Keys.CONSTRAINT_3);

        return _chat;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_36);

        return _link;
    }

    @Override
    @NotNull
    public TrackedLink as(String alias) {
        return new TrackedLink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public TrackedLink as(Name alias) {
        return new TrackedLink(alias, this);
    }

    @Override
    @NotNull
    public TrackedLink as(Table<?> alias) {
        return new TrackedLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackedLink rename(String name) {
        return new TrackedLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackedLink rename(Name name) {
        return new TrackedLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public TrackedLink rename(Table<?> name) {
        return new TrackedLink(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
