app:
  telegram-token: ${token}
  scrapper-base-url: http://localhost:8080

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
