/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.dao.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Question implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private Integer commentsCount;
    private Integer answersCount;

    public Question() {
    }

    public Question(Question value) {
        this.linkId = value.linkId;
        this.commentsCount = value.commentsCount;
        this.answersCount = value.answersCount;
    }

    @ConstructorProperties({"linkId", "commentsCount", "answersCount"})
    public Question(
        @NotNull Long linkId,
        @Nullable Integer commentsCount,
        @Nullable Integer answersCount
    ) {
        this.linkId = linkId;
        this.commentsCount = commentsCount;
        this.answersCount = answersCount;
    }

    /**
     * Getter for <code>QUESTION.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>QUESTION.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>QUESTION.COMMENTS_COUNT</code>.
     */
    @Nullable
    public Integer getCommentsCount() {
        return this.commentsCount;
    }

    /**
     * Setter for <code>QUESTION.COMMENTS_COUNT</code>.
     */
    public void setCommentsCount(@Nullable Integer commentsCount) {
        this.commentsCount = commentsCount;
    }

    /**
     * Getter for <code>QUESTION.ANSWERS_COUNT</code>.
     */
    @Nullable
    public Integer getAnswersCount() {
        return this.answersCount;
    }

    /**
     * Setter for <code>QUESTION.ANSWERS_COUNT</code>.
     */
    public void setAnswersCount(@Nullable Integer answersCount) {
        this.answersCount = answersCount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Question other = (Question) obj;
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        if (this.commentsCount == null) {
            if (other.commentsCount != null) {
                return false;
            }
        } else if (!this.commentsCount.equals(other.commentsCount)) {
            return false;
        }
        if (this.answersCount == null) {
            if (other.answersCount != null) {
                return false;
            }
        } else if (!this.answersCount.equals(other.answersCount)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.commentsCount == null) ? 0 : this.commentsCount.hashCode());
        result = prime * result + ((this.answersCount == null) ? 0 : this.answersCount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Question (");

        sb.append(linkId);
        sb.append(", ").append(commentsCount);
        sb.append(", ").append(answersCount);

        sb.append(")");
        return sb.toString();
    }
}
