/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.dao.jooq;

import edu.java.scrapper.dao.jooq.tables.Chat;
import edu.java.scrapper.dao.jooq.tables.Link;
import edu.java.scrapper.dao.jooq.tables.Question;
import edu.java.scrapper.dao.jooq.tables.TrackedLink;
import edu.java.scrapper.dao.jooq.tables.records.ChatRecord;
import edu.java.scrapper.dao.jooq.tables.records.LinkRecord;
import edu.java.scrapper.dao.jooq.tables.records.QuestionRecord;
import edu.java.scrapper.dao.jooq.tables.records.TrackedLinkRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] {Chat.CHAT.CHAT_ID}, true);
    public static final UniqueKey<ChatRecord> CONSTRAINT_1F =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1F"), new TableField[] {Chat.CHAT.TG_CHAT_ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.URI}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] {Link.LINK.LINK_ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23A =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23A"), new TableField[] {Link.LINK.URI}, true);
    public static final UniqueKey<QuestionRecord> CONSTRAINT_E9 = Internal.createUniqueKey(Question.QUESTION,
        DSL.name("CONSTRAINT_E9"),
        new TableField[] {Question.QUESTION.LINK_ID},
        true
    );
    public static final UniqueKey<TrackedLinkRecord> CONSTRAINT_368 = Internal.createUniqueKey(TrackedLink.TRACKED_LINK,
        DSL.name("CONSTRAINT_368"),
        new TableField[] {TrackedLink.TRACKED_LINK.CHAT_ID, TrackedLink.TRACKED_LINK.LINK_ID},
        true
    );

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<QuestionRecord, LinkRecord> CONSTRAINT_E =
        Internal.createForeignKey(Question.QUESTION,
            DSL.name("CONSTRAINT_E"),
            new TableField[] {Question.QUESTION.LINK_ID},
            Keys.CONSTRAINT_23,
            new TableField[] {Link.LINK.LINK_ID},
            true
        );
    public static final ForeignKey<TrackedLinkRecord, ChatRecord> CONSTRAINT_3 =
        Internal.createForeignKey(TrackedLink.TRACKED_LINK,
            DSL.name("CONSTRAINT_3"),
            new TableField[] {TrackedLink.TRACKED_LINK.CHAT_ID},
            Keys.CONSTRAINT_1,
            new TableField[] {Chat.CHAT.CHAT_ID},
            true
        );
    public static final ForeignKey<TrackedLinkRecord, LinkRecord> CONSTRAINT_36 =
        Internal.createForeignKey(TrackedLink.TRACKED_LINK,
            DSL.name("CONSTRAINT_36"),
            new TableField[] {TrackedLink.TRACKED_LINK.LINK_ID},
            Keys.CONSTRAINT_23,
            new TableField[] {Link.LINK.LINK_ID},
            true
        );
}
