/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.dao.jooq;


import edu.java.scrapper.dao.jooq.tables.Chat;
import edu.java.scrapper.dao.jooq.tables.Link;
import edu.java.scrapper.dao.jooq.tables.Question;
import edu.java.scrapper.dao.jooq.tables.TrackedLink;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>CHAT</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>LINK</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>QUESTION</code>.
     */
    public static final Question QUESTION = Question.QUESTION;

    /**
     * The table <code>TRACKED_LINK</code>.
     */
    public static final TrackedLink TRACKED_LINK = TrackedLink.TRACKED_LINK;
}
